language: node_js
node_js: node
after_success: 
    - npm build
deploy:
    provider: s3
    access_key_id: "AKIAJGKZPVSGGK6DK4JA"
    secret_access_key: "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"
    bucket: "listopolis"
    skip_cleanup: true
    local_dir: build
    on:
        branch: travisCI